### ISSUE TITLE
make run_tests error

### ISSUE THREAD

**Issue by Pawel2013** [GoogleCloudPlatform/cpp-docs-samples#1]
**I am using Ubuntu bash on Windows 10**.
After:
**successful compiling** (and installing) **gRPC** (and **proto3**)
during:
**make run_tests**
Pawel@DESKTOP-HJSUITN:~/cpp-docs-samples/speech/api$ make run_tests
./transcribe -b 16000 resources/audio.raw
E1127 13:29:22.675581700   26963 ev_epoll_linux.c:1655]      pollset_work: {"created":"@1480282162.675479800","descripti
on":"pollset_work_and_unlock","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":268,"referenced_errors":[{"create
d":"@1480282162.675471900","description":"OS Error","errno":38,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":
1486,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 6 failed with error: 38 (Function not imple
mented)"}]}
E1127 13:29:22.677600200   26963 google_default_credentials.c:149] pollset_work: {"created":"@1480282162.675479800","des
cription":"pollset_work_and_unlock","file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":268,"referenced_errors":[{"
created":"@1480282162.675471900","description":"OS Error","errno":38,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_
line":1486,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 6 failed with error: 38 (Function not
 implemented)"}]}
E1127 13:29:22.677996000   26963 google_default_credentials.c:293] Could not create google default credentials.
E1127 13:29:22.678300500   26963 google_default_credentials.c:298] grpc_google_default_credentials_create: {"created":"@
1480282162.668035600","description":"Failed to create Google credentials","file":"src/core/lib/security/credentials/goog
le_default/google_default_credentials.c","file_line":237,"referenced_errors":[{"created":"@1480282162.668040700","descri
ption":"creds_path unset","file":"src/core/lib/security/credentials/google_default/google_default_credentials.c","file_l
ine":181},{"created":"@1480282162.668200400","description":"Failed to load file","file":"src/core/lib/iomgr/load_file.c"
,"file_line":82,"filename":"/home/Pawel/.config/gcloud/application_default_credentials.json","referenced_errors":[{"crea
ted":"@1480282162.668192800","description":"OS Error","errno":2,"file":"src/core/lib/iomgr/load_file.c","file_line":58,"
os_error":"No such file or directory","syscall":"fopen"}]}]}
E1127 13:29:22.841562400   26964 polling_entity.c:101]       Invalid grpc_polling_entity tag '-566067776'

**Comment by SurferJeffAtGoogle** [comment]
It's failing to find your application default credentials.  See:
https://developers.google.com/identity/protocols/application-default-credentials
