### ISSUE TITLE
Assertion failure in grpc call.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/cpp-docs-samples#16]
[Steps to reproduce]
Build `Dockerfile` using the steps found in [Docker.README.md](https://github.com/GoogleCloudPlatform/cpp-docs-samples/blob/master/speech/api/Docker.README.md). 

run: `./streaming_transcribe_singlethread -b 16000 resources/audio.raw` 

[Error]
```
channel_cc.cc:136]        assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)
```

**Comment by kaushik1618** [comment]
Hitting the same issue with "make run_tests" without using Docker.

**Comment by peitaosu** [comment]
Same issue, any comments?

```
./streaming_transcribe_singlethread -b 16000 resources/audio.raw
E0801 00:50:46.761960608  112781 channel_cc.cc:121]          assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)
Makefile:62: recipe for target 'run_tests' failed
make: *** [run_tests] Aborted (core dumped)
```

**Comment by jobchoi** [comment]
ubunto :16.04 
cpp 
cpp-docs-samples/speech/api -> make run_tests 
result : 
./transcribe -b 16000 resources/audio.raw
E0124 11:30:00.650999289   25514 json_util.cc:33]            Invalid or missing type property.
E0124 11:30:00.651130758   25514 json_util.cc:33]            Invalid or missing type property.
E0124 11:30:00.651163556   25514 google_default_credentials.cc:213] assertion failed: (result == nullptr) + (error == GRPC_ERROR_NONE) == 1
Makefile:63: recipe for target 'run_tests' failed
make: *** [run_tests] Aborted (core dumped)

how to use make run_tests?
