### ISSUE TITLE
Google Cloud Speech API 

### ISSUE THREAD

**Issue by jopedroliveira** [GoogleCloudPlatform/cpp-docs-samples#17]
According to google the Google Cloud Speech API is now Generally Available.
Within this change, some other changes were made on the api.
Does it influences this demo program?  What kind of changes are needed to migrate this demo to the new GCSAPI version?

**Comment by coryan** [comment]
AFAICT the examples are using the same APIs documented in google.cloud.com/speech/.  I recently compiled the examples and used them, they seem to work Okay.  In other words, I think the answer to your questions are:  no changes are needed to migrate this demo.  If you find some specific that needs changes please feel free to reopen the issue.
