### ISSUE TITLE
Success on Linux (partially)

### ISSUE THREAD

**Issue by Pawel2013** [GoogleCloudPlatform/cpp-docs-samples#3]
I confirm possibility of building on Linux platform:
Linux Mint - yes.
openSuse - yes:
Ubunty - NO.

Is there any chance on Windows (MinGW or VS 2015) ?

**Comment by SurferJeffAtGoogle** [comment]
What error do you see on Ubuntu?

**Comment by SurferJeffAtGoogle** [comment]
If you see this issue again, please reopen.
