### ISSUE TITLE
TSI_INTERNAL_ERROR "Sending protected frame to ssl failed with -1" GRPC issue

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/cpp-docs-samples#33]
When running "make run_tests" the very last check "./transcribe -b 16000 resources/audio.raw" fails with message **"Sending protected frame to ssl failed with -1"**.

I understand this is an issue with grpc, but I am also able to run client server helloworld there just fine (I'm talking about this: https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld). 

Any idea what could be causing this?

**Comment by tmatsuo** [comment]
@ghost We added an integration tests for that. We haven't seen that error yet. Is it possible for you to provide a way to reproduce the error?

**Comment by tmatsuo** [comment]
Since we haven't reproduce this yet, let me close this, but feel free to reopen this with repro step.
