### ISSUE TITLE
Could not create google default credentials

### ISSUE THREAD

**Issue by Rohan0993** [GoogleCloudPlatform/cpp-docs-samples#50]
Hi All,
I am working on the Opensuse Leap 155.0 for running these tests.
I have installed protobuf and grpc successfully, and trying to make the **cpp-docs-samples > speech > api> make run_tests**. I am getting this error

[Error.txt](https://github.com/GoogleCloudPlatform/cpp-docs-samples/files/2832254/Error.txt)

`sudo make run_tests`

`./transcribe -b 16000 resources/audio.raw
E0205 18:55:48.361527397    3233 google_default_credentials.cc:350] Could not create google default credentials: {"created":"@1549373148.360106566","description":"Failed to create Google credentials","file":"src/core/lib/security/credentials/google_default/google_default_credentials.cc","file_line":284,"referenced_errors":[{"created":"@1549373148.360126434","description":"Failed to load file","file":"src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"home/rohan/Downloads/proven-caster-222406-5522480516c5.json","referenced_errors":[{"created":"@1549373148.360123641","description":"No such file or directory","errno":2,"file":"src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]},{"created":"@1549373148.360135072","description":"Failed to load file","file":"src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"/root/.config/gcloud/application_default_credentials.json","referenced_errors":[{"created":"@1549373148.360134709","description":"No such file or directory","errno":2,"file":"src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}]}
lame client channel
make: *** [Makefile:63: run_tests] Error 255
`

Can someone help me with this?

**Comment by coryan** [comment]
Looks like you do not have your credentials configured:

https://cloud.google.com/docs/authentication/getting-started

Did you try using `gcloud` first to verify the authentication works?

https://cloud.google.com/speech-to-text/docs/quickstart-gcloud

**Comment by Rohan0993** [comment]
Hi @coryan I have followed the above links. I have a service account with owner role. and I have set up the gcloud.

I can access the gcloud commands from the google-cloud-sdk directory. 

But I am not sure why do I need this. It did not make any visual difference in the behaviour of my question. Did I do it right?

**Comment by Rohan0993** [comment]
`┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                  Components                                                 │
├───────────────┬──────────────────────────────────────────────────────┬──────────────────────────┬───────────┤
│     Status    │                         Name                         │            ID            │    Size   │
├───────────────┼──────────────────────────────────────────────────────┼──────────────────────────┼───────────┤
│ Not Installed │ App Engine Go Extensions                             │ app-engine-go            │  56.6 MiB │
│ Not Installed │ Cloud Bigtable Command Line Tool                     │ cbt                      │   6.4 MiB │
│ Not Installed │ Cloud Bigtable Emulator                              │ bigtable                 │   5.6 MiB │
│ Not Installed │ Cloud Datalab Command Line Tool                      │ datalab                  │   < 1 MiB │
│ Not Installed │ Cloud Datastore Emulator (Legacy)                    │ gcd-emulator             │  38.1 MiB │
│ Not Installed │ Cloud Firestore Emulator                             │ cloud-firestore-emulator │  32.1 MiB │
│ Not Installed │ Cloud Pub/Sub Emulator                               │ pubsub-emulator          │  33.4 MiB │
│ Not Installed │ Cloud SQL Proxy                                      │ cloud_sql_proxy          │   3.8 MiB │
│ Not Installed │ Emulator Reverse Proxy                               │ emulator-reverse-proxy   │  14.5 MiB │
│ Not Installed │ Google Cloud Build Local Builder                     │ cloud-build-local        │   6.0 MiB │
│ Not Installed │ Google Container Registry's Docker credential helper │ docker-credential-gcr    │   1.8 MiB │
│ Not Installed │ gcloud Alpha Commands                                │ alpha                    │   < 1 MiB │
│ Not Installed │ gcloud Beta Commands                                 │ beta                     │   < 1 MiB │
│ Not Installed │ gcloud app Java Extensions                           │ app-engine-java          │ 107.5 MiB │
│ Not Installed │ gcloud app PHP Extensions                            │ app-engine-php           │           │
│ Not Installed │ gcloud app Python Extensions (Extra Libraries)       │ app-engine-python-extras │  28.5 MiB │
│ Not Installed │ kubectl                                              │ kubectl                  │   < 1 MiB │
│ Installed     │ BigQuery Command Line Tool                           │ bq                       │   < 1 MiB │
│ Installed     │ Cloud Datastore Emulator                             │ cloud-datastore-emulator │  18.4 MiB │
│ Installed     │ Cloud SDK Core Libraries                             │ core                     │   9.4 MiB │
│ Installed     │ Cloud Storage Command Line Tool                      │ gsutil                   │   3.6 MiB │
│ Installed     │ gcloud app Python Extensions                         │ app-engine-python        │   6.2 MiB │
└───────────────┴──────────────────────────────────────────────────────┴──────────────────────────┴───────────┘`

**Comment by coryan** [comment]
The error message is what you get from gRPC when the credentials are not setup, it is very hidden, but it says:

```
{"created":"@1549373148.360135072","description":
"Failed to load file",

"file":"src/core/lib/iomgr/load_file.cc","file_line":71,

"filename":"/root/.config/gcloud/application_default_credentials.json",
```

That is, gRPC tried to open `/root/.config/gcloud/application_default_credentials.json` and failed, and that file is where the application default credentials are usually stored for `root`.

And only after writing that I noticed that you are doing a `sudo make`. I suspect *your* account has credentials, but `root` does not (and probably should not).  You probably want to run `make tests` without the `sudo`.

**Comment by Rohan0993** [comment]
Ohh genius ! Yay that worked :)

**Comment by coryan** [comment]
Glad to hear that, closing this bug.
